### PR TITLE
fix: include typings for entry.nostyle.d.ts.  Fixes #33

### LINKED ISSUE #33: The typings are not fetched for entry.nostyle
May be fixed by creating `entry.nostyle.d.ts` ether copypasting `index.d.ts` or importing it and exporting each of it's own exports.

### PR DESCRIPTION
**Pull request by szdc**
I'm not an expert in TypeScript either but this is what I could come up with.  There's no code duplication, and the reason I copy the file to the `dist` folder is because if it isn't alongside the corresponding `js` file, it doesn't get resolved.

Fixes #33

### CODE REVIEW

File: copy-types.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+const fs = require('fs');
```
Comment (wojtekmaj) [inline copy-types.js]: I don't know if I understand - why do we need this file? `index.d.ts` lands in distribution package automatically just because it's added to `files` in `package.json` - wouldn't that happen for `entry.nostyle.d.ts` too?

**Comment by wojtekmaj** [comment]
Thank you so much for this contribution!
